### ISSUE TITLE
[Setting] 프로젝트 세팅 

### ISSUE THREAD

**Issue by 6uohul** [team-winey/Winey-iOS#1]
## 🛠 Issue

프로젝트 초기 세팅

## 📝 To-do

- [ ] 폴더링
- [ ] 라이브러리 추가
- [ ] 탭 바 컨드롤러 생성
- [ ] 에셋 및 폰트 1차 추가
- [ ] 기타 세팅

**Comment by GodSamble** [comment]
밥먹으러가요..
