### ISSUE TITLE
[Fix] 절약 목표 뷰 수정

### ISSUE THREAD

**Issue by 6uohul** [team-winey/Winey-iOS#71]
## 🛠 Issue

스크롤 뷰로 수정

## 📝 To-do

- [x] 스크롤 뷰
- [x] 키보드 올라올 때 버튼 위치 수정
- [x] 목표 저장 버튼 enable 분기처리

**Comment by samsung-ga** [comment]
추가적으로 디테일뷰 레이아웃 수정이 들어가야해서 리오픈합니다.
